# Generated by Django 5.1.5 on 2025-01-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='номер стола')),
                ('items', models.JSONField(verbose_name='список блюд')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('ready', 'готово'), ('pending', 'в ожидании'), ('paid', 'оплачено')], default='pending', max_length=20, verbose_name='статус заказа')),
            ],
        ),
    ]
