# Generated by Django 5.1.5 on 2025-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', 'готово'), ('waiting', 'в ожидании'), ('paid', 'оплачено')], default='pending', max_length=20, verbose_name='статус заказа'),
        ),
    ]
