# Generated by Django 5.1.5 on 2025-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('готово', 'готово'), ('в ожидании', 'в ожидании'), ('оплачено', 'оплачено')], default='pending', max_length=20, verbose_name='статус заказа'),
        ),
    ]
